// <auto-generated />
using System;
using GreenForest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenForest.Migrations
{
    [DbContext(typeof(GreenForestContext))]
    partial class GreenForestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenForest.Models.Arbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<int>("EspecieId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Arboles");
                });

            modelBuilder.Entity("GreenForest.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClimaIdeal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DistanciaSiembra")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HumedadMaxima")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HumedadMinima")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecipitacionMaxima")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecipitacionMinima")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TemperaturaMaxima")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TemperaturaMinima")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoSuelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ToleranciaSequía")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("GreenForest.Models.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones");
                });

            modelBuilder.Entity("GreenForest.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MetaArboles")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetaHectareas")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("OrganizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("GreenForest.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadArboles")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("GreenForest.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GreenForest.Models.Arbol", b =>
                {
                    b.HasOne("GreenForest.Models.Especie", "Especie")
                        .WithMany("Arboles")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenForest.Models.Proyecto", "Proyecto")
                        .WithMany("Arboles")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GreenForest.Models.Proyecto", b =>
                {
                    b.HasOne("GreenForest.Models.Organizacion", "Organizacion")
                        .WithMany("Proyectos")
                        .HasForeignKey("OrganizacionId");

                    b.HasOne("GreenForest.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GreenForest.Models.Reporte", b =>
                {
                    b.HasOne("GreenForest.Models.Proyecto", "Proyecto")
                        .WithMany("Reportes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GreenForest.Models.Especie", b =>
                {
                    b.Navigation("Arboles");
                });

            modelBuilder.Entity("GreenForest.Models.Organizacion", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("GreenForest.Models.Proyecto", b =>
                {
                    b.Navigation("Arboles");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
